-- 07_qualifications.sql
-- Populates qualifications tables from Countries, LAD25, Regions source tables
-- Run rename-socio-columns.js first to fix the blocked source column name.

TRUNCATE TABLE "Socioeconomics".countries_qualifications;
INSERT INTO "Socioeconomics".countries_qualifications (
  ctry24cd,
  total_residents_16_over,
  all_residents_qual, all_residents_qual_pct,
  no_qualifications, no_qualifications_pct,
  level_1_entry, level_1_entry_pct,
  level_2, level_2_pct,
  apprenticeship, apprenticeship_pct,
  level_3, level_3_pct,
  level_4_above, level_4_above_pct,
  other_qualifications, other_qualifications_pct,
  no_qualifications_2, no_qualifications_pct_2,
  level_1_entry_2, level_1_entry_pct_2,
  level_2_2, level_2_pct_2,
  apprenticeship_2, apprenticeship_pct_2,
  level_3_2, level_3_pct_2,
  level_4_above_2, level_4_above_pct_2,
  other_qualifications_2, other_qualifications_pct_2
)
SELECT
  "CTRY24CD",
  "Master sheet2_Total_All_usual_residents_aged_16_and_over",
  "Master sheet2_All usual residents qualification",
  "Master sheet2_All usual residents qualification percent",
  "Master sheet2_No qualifications",
  "Master sheet2_No qualifications percent",
  "Master sheet2_Level 1 and entry level qualifications",
  "Master sheet2_Level 1 and entry level qualifications percent",
  "Master sheet2_Level 2 qualifications",
  "Master sheet2_Level 2 qualifications percent",
  "Master sheet2_Apprenticeship",
  "Master sheet2_Apprenticeship percent",
  "Master sheet2_Level 3 qualifications",
  "Master sheet2_Level 3 qualifications percent",
  "Master sheet2_Level 4 qualifications or above",
  "Master sheet2_Level 4 qualifications or above percent",
  "Master sheet2_Other qualifications",
  "Master sheet2_Other qualifications percent",
  "Master sheet2_No qualifications_1",
  "Master sheet2_No qualifications percent_1",
  "Master sheet2_Level 1 and entry level qualifications_1",
  "Master sheet2_Level 1 and entry level qualifications percent_1",
  "Master sheet2_Level 2 qualifications_1",
  "Master sheet2_Level 2 qualifications percent_1",
  "Master sheet2_Apprenticeship_1",
  "Master sheet2_Apprenticeship percent_1",
  "Master sheet2_Level 3 qualifications_1",
  "Master sheet2_Level 3 qualifications percent_1",
  "Master sheet2_Level 4 qualifications or above_1",
  "Master sheet2_Level 4 qualifications or above percent_1",
  "Master sheet2_Other qualifications_1",
  "Master sheet2_Other qualifications percent_1"
FROM "Socioeconomics"."Countries";

TRUNCATE TABLE "Socioeconomics".lad25_qualifications;
INSERT INTO "Socioeconomics".lad25_qualifications (
  lad23cd,
  total_residents_16_over,
  all_residents_qual, all_residents_qual_pct,
  no_qualifications, no_qualifications_pct,
  level_1_entry, level_1_entry_pct,
  level_2, level_2_pct,
  apprenticeship, apprenticeship_pct,
  level_3, level_3_pct,
  level_4_above, level_4_above_pct,
  other_qualifications, other_qualifications_pct,
  no_qualifications_2, no_qualifications_pct_2,
  level_1_entry_2, level_1_entry_pct_2,
  level_2_2, level_2_pct_2,
  apprenticeship_2, apprenticeship_pct_2,
  level_3_2, level_3_pct_2,
  level_4_above_2, level_4_above_pct_2,
  other_qualifications_2, other_qualifications_pct_2
)
SELECT
  "LAD23CD",
  "Master sheet2_Total_All_usual_residents_aged_16_and_over",
  "Master sheet2_All usual residents qualification",
  "Master sheet2_All usual residents qualification percent",
  "Master sheet2_No qualifications",
  "Master sheet2_No qualifications percent",
  "Master sheet2_Level 1 and entry level qualifications",
  "Master sheet2_Level 1 and entry level qualifications percent",
  "Master sheet2_Level 2 qualifications",
  "Master sheet2_Level 2 qualifications percent",
  "Master sheet2_Apprenticeship",
  "Master sheet2_Apprenticeship percent",
  "Master sheet2_Level 3 qualifications",
  "Master sheet2_Level 3 qualifications percent",
  "Master sheet2_Level 4 qualifications or above",
  "Master sheet2_Level 4 qualifications or above percent",
  "Master sheet2_Other qualifications",
  "Master sheet2_Other qualifications percent",
  "Master sheet2_No qualifications_1",
  "Master sheet2_No qualifications percent_1",
  "Master sheet2_Level 1 and entry level qualifications_1",
  "Master sheet2_Level 1 and entry level qualifications percent_1",
  "Master sheet2_Level 2 qualifications_1",
  "Master sheet2_Level 2 qualifications percent_1",
  "Master sheet2_Apprenticeship_1",
  "Master sheet2_Apprenticeship percent_1",
  "Master sheet2_Level 3 qualifications_1",
  "Master sheet2_Level 3 qualifications percent_1",
  "Master sheet2_Level 4 qualifications or above_1",
  "Master sheet2_Level 4 qualifications or above percent_1",
  "Master sheet2_Other qualifications_1",
  "Master sheet2_Other qualifications percent_1"
FROM "Socioeconomics"."LAD25";

TRUNCATE TABLE "Socioeconomics".regions_qualifications;
INSERT INTO "Socioeconomics".regions_qualifications (
  rgn24cd,
  total_residents_16_over,
  all_residents_qual, all_residents_qual_pct,
  no_qualifications, no_qualifications_pct,
  level_1_entry, level_1_entry_pct,
  level_2, level_2_pct,
  apprenticeship, apprenticeship_pct,
  level_3, level_3_pct,
  level_4_above, level_4_above_pct,
  other_qualifications, other_qualifications_pct,
  no_qualifications_2, no_qualifications_pct_2,
  level_1_entry_2, level_1_entry_pct_2,
  level_2_2, level_2_pct_2,
  apprenticeship_2, apprenticeship_pct_2,
  level_3_2, level_3_pct_2,
  level_4_above_2, level_4_above_pct_2,
  other_qualifications_2, other_qualifications_pct_2
)
SELECT
  "RGN24CD",
  "Master sheet2_Total_All_usual_residents_aged_16_and_over",
  "Master sheet2_All usual residents qualification",
  "Master sheet2_All usual residents qualification percent",
  "Master sheet2_No qualifications",
  "Master sheet2_No qualifications percent",
  "Master sheet2_Level 1 and entry level qualifications",
  "Master sheet2_Level 1 and entry level qualifications percent",
  "Master sheet2_Level 2 qualifications",
  "Master sheet2_Level 2 qualifications percent",
  "Master sheet2_Apprenticeship",
  "Master sheet2_Apprenticeship percent",
  "Master sheet2_Level 3 qualifications",
  "Master sheet2_Level 3 qualifications percent",
  "Master sheet2_Level 4 qualifications or above",
  "Master sheet2_Level 4 qualifications or above percent",
  "Master sheet2_Other qualifications",
  "Master sheet2_Other qualifications percent",
  "Master sheet2_No qualifications_1",
  "Master sheet2_No qualifications percent_1",
  "Master sheet2_Level 1 and entry level qualifications_1",
  "Master sheet2_Level 1 and entry level qualifications percent_1",
  "Master sheet2_Level 2 qualifications_1",
  "Master sheet2_Level 2 qualifications percent_1",
  "Master sheet2_Apprenticeship_1",
  "Master sheet2_Apprenticeship percent_1",
  "Master sheet2_Level 3 qualifications_1",
  "Master sheet2_Level 3 qualifications percent_1",
  "Master sheet2_Level 4 qualifications or above_1",
  "Master sheet2_Level 4 qualifications or above percent_1",
  "Master sheet2_Other qualifications_1",
  "Master sheet2_Other qualifications percent_1"
FROM "Socioeconomics"."Regions";
